In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)


In [7]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV

param_grid = {'priors':[None],
             'var_smoothing':[1e-09]}

grid = GridSearchCV(GaussianNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 

grid.fit(X_train, y_train) 

re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)





Fitting 5 folds for each of 1 candidates, totalling 5 fits
The f1_macro value for best parameter {'priors': None, 'var_smoothing': 1e-09}: 0.9022944298888885
The confusion Matrix:
 [[80  5]
 [ 8 41]]
The report:
               precision    recall  f1-score   support

           0       0.91      0.94      0.92        85
           1       0.89      0.84      0.86        49

    accuracy                           0.90       134
   macro avg       0.90      0.89      0.89       134
weighted avg       0.90      0.90      0.90       134



In [8]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])



0.9625450180072028

In [9]:
table=pd.DataFrame.from_dict(re)
table


mean_fit_time  std_fit_time  mean_score_time  std_score_time param_priors  \
0       0.009997      0.002446         0.012988        0.003158         None   

  param_var_smoothing                                    params  \
0                 0.0  {'priors': None, 'var_smoothing': 1e-09}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0           0.822092           0.868752           0.813179           0.962264   

   split4_test_score  mean_test_score  std_test_score  rank_test_score  
0           0.961755         0.885608        0.065175                1

In [10]:
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import GridSearchCV

param_grid = {'alpha':[1.0],
              'force_alpha':[True,False],
              'fit_prior':[True,False]}


grid = GridSearchCV(CategoricalNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 

grid.fit(X_train, y_train) 
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)





Fitting 5 folds for each of 4 candidates, totalling 20 fits
The f1_macro value for best parameter {'alpha': 1.0, 'fit_prior': True, 'force_alpha': True}: 0.8354758282828774
The confusion Matrix:
 [[82  3]
 [18 31]]
The report:
               precision    recall  f1-score   support

           0       0.82      0.96      0.89        85
           1       0.91      0.63      0.75        49

    accuracy                           0.84       134
   macro avg       0.87      0.80      0.82       134
weighted avg       0.85      0.84      0.84       134



C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan]
  warnings.warn(


In [11]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])



0.8955582232893157

In [12]:
table=pd.DataFrame.from_dict(re)
table


mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.059562      0.016526         0.022188        0.004164         1.0   
1       0.053170      0.019412         0.015788        0.002636         1.0   
2       0.041573      0.003717         0.016592        0.005458         1.0   
3       0.039571      0.006373         0.011792        0.002925         1.0   

  param_fit_prior param_force_alpha  \
0            True              True   
1            True             False   
2           False              True   
3           False             False   

                                              params  split0_test_score  \
0  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.726566   
1  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.726566   
2  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.735616   
3  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.735616   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.776838           0.673750           0.818941                NaN   
1           0.776838           0.673750           0.818941                NaN   
2           0.828959           0.710831           0.869709                NaN   
3           0.828959           0.710831           0.869709                NaN   

   mean_test_score  std_test_score  rank_test_score  
0              NaN             NaN                1  
1              NaN             NaN                1  
2              NaN             NaN                1  
3              NaN             NaN                1

In [13]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])


0.8955582232893157

In [14]:
table=pd.DataFrame.from_dict(re)
table


mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.059562      0.016526         0.022188        0.004164         1.0   
1       0.053170      0.019412         0.015788        0.002636         1.0   
2       0.041573      0.003717         0.016592        0.005458         1.0   
3       0.039571      0.006373         0.011792        0.002925         1.0   

  param_fit_prior param_force_alpha  \
0            True              True   
1            True             False   
2           False              True   
3           False             False   

                                              params  split0_test_score  \
0  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.726566   
1  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.726566   
2  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.735616   
3  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.735616   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.776838           0.673750           0.818941                NaN   
1           0.776838           0.673750           0.818941                NaN   
2           0.828959           0.710831           0.869709                NaN   
3           0.828959           0.710831           0.869709                NaN   

   mean_test_score  std_test_score  rank_test_score  
0              NaN             NaN                1  
1              NaN             NaN                1  
2              NaN             NaN                1  
3              NaN             NaN                1

In [15]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV

param_grid = {'alpha':[1.0],
              'force_alpha':[True,False],
              'fit_prior':[True,False],
              'binarize':[0.5]}


grid = GridSearchCV(BernoulliNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 

grid.fit(X_train, y_train) 

re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)



Fitting 5 folds for each of 4 candidates, totalling 20 fits
The f1_macro value for best parameter {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': False, 'force_alpha': True}: 0.4942225312442918
The confusion Matrix:
 [[40 45]
 [24 25]]
The report:
               precision    recall  f1-score   support

           0       0.62      0.47      0.54        85
           1       0.36      0.51      0.42        49

    accuracy                           0.49       134
   macro avg       0.49      0.49      0.48       134
weighted avg       0.53      0.49      0.49       134



In [16]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])




0.49039615846338536

In [17]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.012193      0.001939         0.016989        0.001895         1.0   
1       0.015791      0.004442         0.013991        0.002606         1.0   
2       0.010992      0.001095         0.014592        0.002243         1.0   
3       0.009193      0.001165         0.012393        0.002576         1.0   

  param_binarize param_fit_prior param_force_alpha  \
0            0.5            True              True   
1            0.5            True             False   
2            0.5           False              True   
3            0.5           False             False   

                                              params  split0_test_score  \
0  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': T...           0.509779   
1  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': T...           0.509779   
2  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': F...           0.509839   
3  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': F...           0.509839   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.525300           0.501410           0.501410           0.501410   
1           0.525300           0.501410           0.501410           0.501410   
2           0.539529           0.482156           0.630298           0.555303   
3           0.539529           0.482156           0.630298           0.555303   

   mean_test_score  std_test_score  rank_test_score  
0         0.507862        0.009302                3  
1         0.507862        0.009302                3  
2         0.543425        0.050170                1  
3         0.543425        0.050170                1

In [18]:
from sklearn.naive_bayes import ComplementNB 
from sklearn.model_selection import GridSearchCV

param_grid = {'alpha':[1.0],
              'force_alpha':[True,False],
              'fit_prior':[True,False],
              'norm':[True,False]}


grid = GridSearchCV(ComplementNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 

grid.fit(X_train, y_train) 

Fitting 5 folds for each of 8 candidates, totalling 40 fits


GridSearchCV(estimator=ComplementNB(), n_jobs=-1,
             param_grid={'alpha': [1.0], 'fit_prior': [True, False],
                         'force_alpha': [True, False], 'norm': [True, False]},
             scoring='f1_weighted', verbose=3)

In [19]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)


In [20]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)


The f1_macro value for best parameter {'alpha': 1.0, 'fit_prior': True, 'force_alpha': True, 'norm': False}: 0.5224047968734963


In [21]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[40 45]
 [20 29]]


In [22]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.67      0.47      0.55        85
           1       0.39      0.59      0.47        49

    accuracy                           0.51       134
   macro avg       0.53      0.53      0.51       134
weighted avg       0.57      0.51      0.52       134



In [23]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])



0.5846338535414165

In [24]:
table=pd.DataFrame.from_dict(re)

In [25]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.014391      0.004583         0.013990        0.002279         1.0   
1       0.016989      0.008094         0.014991        0.007011         1.0   
2       0.013596      0.003499         0.014386        0.002331         1.0   
3       0.011191      0.001164         0.012393        0.002059         1.0   
4       0.011593      0.002416         0.013192        0.001938         1.0   
5       0.010394      0.001019         0.012392        0.001019         1.0   
6       0.010792      0.001326         0.013796        0.002709         1.0   
7       0.008992      0.001093         0.011393        0.002415         1.0   

  param_fit_prior param_force_alpha param_norm  \
0            True              True       True   
1            True              True      False   
2            True             False       True   
3            True             False      False   
4           False              True       True   
5           False              True      False   
6           False             False       True   
7           False             False      False   

                                              params  split0_test_score  \
0  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.183156   
1  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.509839   
2  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.183156   
3  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.509839   
4  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.183156   
5  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.509839   
6  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.183156   
7  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.509839   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.172203           0.189203           0.189203           0.189203   
1           0.614012           0.563318           0.482156           0.556133   
2           0.172203           0.189203           0.189203           0.189203   
3           0.614012           0.563318           0.482156           0.556133   
4           0.172203           0.189203           0.189203           0.189203   
5           0.614012           0.563318           0.482156           0.556133   
6           0.172203           0.189203           0.189203           0.189203   
7           0.614012           0.563318           0.482156           0.556133   

   mean_test_score  std_test_score  rank_test_score  
0         0.184594        0.006623                5  
1         0.545092        0.045624                1  
2         0.184594        0.006623                5  
3         0.545092        0.045624                1  
4         0.184594        0.006623                5  
5         0.545092        0.045624                1  
6         0.184594        0.006623                5  
7         0.545092        0.045624                1

In [ ]:
Age_input=float(input("Age:"))
Estimatedsalary_input=float(input("Estimatedsalary:"))
Gender_Male_input=int(input("Gender Male 0 or 1:"))


In [ ]:
Future_Prediction=grid.predict([[Age_input,Estimatedsalary_input,Gender_Male_input]]) 
print("Future_Prediction={}".format(Future_Prediction))